# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutopilotPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_monthly_savings_pct', models.FloatField(default=30.0, help_text='Maximum % of total spend that autopilot can optimize per month')),
                ('allow_stop', models.BooleanField(default=False)),
                ('allow_resize', models.BooleanField(default=False)),
                ('allow_delete', models.BooleanField(default=False)),
                ('max_resources_per_day', models.IntegerField(default=3)),
                ('require_approval', models.BooleanField(default=True)),
                ('enable_kill_switch', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutopilotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('OBSERVE', 'OBSERVE'), ('EXECUTE_SAFE', 'EXECUTE_SAFE'), ('FULL_AUTOPILOT', 'FULL_AUTOPILOT')], default='OBSERVE')),
                ('max_risk_allowed', models.FloatField(default=0.25)),
            ],
        ),
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=20)),
                ('role_arn', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopilot_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('VIEWER', 'VIEWER')], default='OWNER')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EBSVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_id', models.CharField(max_length=32)),
                ('volume_type', models.CharField(max_length=20)),
                ('size_gb', models.IntegerField()),
                ('iops', models.IntegerField(blank=True, null=True)),
                ('throughput', models.IntegerField(blank=True, null=True)),
                ('attached_instance_id', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(max_length=20)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.awsaccount')),
            ],
        ),
    ]
