# Generated by Django 4.2.8 on 2026-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotsettings',
            name='mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('RECOMMEND', 'Recommend Only'), ('AUTO_SAFE', 'Auto Safe'), ('AUTO_AGGRESSIVE', 'Auto Aggressive')], default='OFF', max_length=20),
        ),
    ]
