# Generated by Django 4.2.8 on 2026-03-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_autopilotsettings_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsafety',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_safety', to='accounts.organization'),
        ),
    ]
