# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('auto_execute_allowed', models.BooleanField()),
                ('reason', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=32)),
                ('namespace', models.CharField(max_length=64)),
                ('target_name', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('parameters', models.JSONField()),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('canary', 'Canary'), ('committed', 'Committed'), ('rolled_back', 'Rolled Back'), ('failed', 'Failed')], default='planned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Policy', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cloud_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='cloud.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('execution_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.executionplan')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.policy')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('current_state', models.JSONField()),
                ('proposed_state', models.JSONField()),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PLANNED', max_length=20)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DETECTED', 'Detected'), ('PLANNED', 'Planned'), ('SIMULATED', 'Simulated'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('VERIFIED', 'Verified'), ('COMPLETED', 'Completed'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed')], default='DETECTED', max_length=20)),
                ('before_state', models.JSONField()),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('rollback_payload', models.JSONField()),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.decision')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.optimizationplan'),
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('estimated_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('is_safe', models.BooleanField(default=True)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudresource')),
            ],
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('executing', 'Executing'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], max_length=16)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('action_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.actionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ActionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('action_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='actions.actionplan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
