# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('kubernetes', 'Kubernetes')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('provider', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k8s_clusters', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='K8sWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('cpu_request', models.FloatField()),
                ('cpu_limit', models.FloatField(blank=True, null=True)),
                ('mem_request', models.IntegerField()),
                ('mem_limit', models.IntegerField(blank=True, null=True)),
                ('replicas', models.IntegerField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.k8scluster')),
            ],
        ),
        migrations.CreateModel(
            name='K8sNodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('instance_type', models.CharField(max_length=64)),
                ('min_nodes', models.IntegerField()),
                ('max_nodes', models.IntegerField()),
                ('desired_nodes', models.IntegerField()),
                ('pricing_model', models.CharField(choices=[('on_demand', 'On-Demand'), ('spot', 'Spot')], max_length=20)),
                ('cpu_capacity', models.FloatField()),
                ('mem_capacity', models.IntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.k8scluster')),
            ],
        ),
        migrations.CreateModel(
            name='GPUWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_type', models.CharField(max_length=32)),
                ('gpu_count', models.IntegerField()),
                ('utilization_avg', models.FloatField()),
                ('utilization_p95', models.FloatField()),
                ('workload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cloud.k8sworkload')),
            ],
        ),
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_identifier', models.CharField(max_length=128)),
                ('role_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('observe', 'Observe'), ('recommend', 'Recommend'), ('autopilot', 'Autopilot')], default='observe', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_accounts', to='accounts.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CloudResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('vm', 'Virtual Machine'), ('db', 'Database'), ('bucket', 'Object Storage'), ('volume', 'Block Storage'), ('gpu', 'GPU'), ('pod', 'Kubernetes Pod')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('cost_per_hour', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='cloud.cloudaccount')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudprovider')),
            ],
            options={
                'unique_together': {('cloud_account', 'external_id')},
            },
        ),
    ]
