# Generated by Django 4.2.8 on 2026-02-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstancePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('operating_system', models.CharField(default='linux', max_length=32)),
                ('pricing_model', models.CharField(choices=[('on_demand', 'On-Demand'), ('spot', 'Spot')], default='on_demand', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=6, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudprovider')),
            ],
            options={
                'unique_together': {('provider', 'instance_type', 'region', 'operating_system', 'pricing_model')},
            },
        ),
    ]
