# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('accounts', '0001_initial'),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SavingsAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=255)),
                ('baseline_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('gross_savings', models.DecimalField(decimal_places=6, max_digits=14)),
                ('net_savings', models.DecimalField(decimal_places=6, max_digits=14)),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.executionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=128)),
                ('before_cost', models.FloatField()),
                ('after_cost', models.FloatField()),
                ('savings', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('checksum', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.savingsattribution')),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(max_length=20)),
                ('resource_id', models.CharField(max_length=128)),
                ('baseline_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action_id', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('PAYPAL', 'PAYPAL'), ('STRIPE', 'STRIPE'), ('MANUAL', 'MANUAL')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('savings_ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.savingsledger')),
            ],
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=128)),
                ('cost_usd', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BaselineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(max_length=20)),
                ('baseline_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('ROLLING_30', 'Rolling 30 days'), ('LAST_MONTH', 'Last month')], max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.FloatField(default=20.0)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_shares', to='accounts.organization')),
                ('savings_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share', to='billing.savingsevent')),
            ],
            options={
                'unique_together': {('organization', 'savings_event')},
            },
        ),
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudaccount')),
            ],
            options={
                'unique_together': {('cloud_account', 'resource_id', 'date')},
            },
        ),
    ]
