# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=128)),
                ('max_latency_ms', models.IntegerField()),
                ('max_error_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=64)),
                ('max_value', models.FloatField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudresource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cloud.cloudresource')),
            ],
        ),
        migrations.CreateModel(
            name='NodeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=128)),
                ('node_name', models.CharField(max_length=128)),
                ('cpu_used', models.FloatField()),
                ('cpu_total', models.FloatField()),
                ('mem_used', models.IntegerField()),
                ('mem_total', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cluster_id', 'node_name', 'timestamp'], name='monitoring__cluster_78171e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('allow_autopilot', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
    ]
