# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('cpu_hours', models.FloatField(default=0)),
                ('memory_gb_hours', models.FloatField(default=0)),
                ('weight', models.FloatField()),
                ('cloud_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_usages', to='cloud.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=64)),
                ('expected_monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudresource')),
            ],
        ),
    ]
