# Generated by Django 4.2.8 on 2026-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=128, null=True)),
                ('cloud', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('before_state', models.JSONField()),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(editable=False, max_length=128)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudaccount')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
